apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: workshop-tls-cert
  namespace: ingress-nginx
spec:
  commonName: '*.workshop.metakube.org'
  dnsNames:
    - '*.workshop.metakube.org'
  secretName: metakube-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
