ingress:
  enabled: true
  hosts:
   - kibana-<YOUR_NAME>.workshop.metakube.org
  annotations:
   kubernetes.io/ingress.class: nginx
   # type of authentication
   nginx.ingress.kubernetes.io/auth-type: basic
   # name of the secret that contains the user/password definitions
   nginx.ingress.kubernetes.io/auth-secret: basic-auth
  tls:
   - hosts:
      - kibana-<YOUR_NAME>.workshop.metakube.org
