apiVersion: v1
kind: Endpoints
metadata:
  # The endpoint name has to be equivalent to the service name!
  name: mysql
subsets:
  - addresses:
      - ip: 10.129.0.1
    ports:
      - name: mysql
        port: 3306
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  # The endpoint name has to be equivalent to the service name!
  name: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  type: ClusterIP
